"""Dashboard and analytics service (Task 3.7)."""

import logging
from typing import Dict, Optional, List
from dataclasses import dataclass
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class DashboardKPIs:
    """Unified KPI dashboard."""

    churn_rate: float  # % of customers churned
    churn_rate_change: float  # % point change from previous period
    avg_ltv: float  # Average customer LTV
    ltv_change_pct: float  # % change YoY
    cart_recovery_rate: float  # % of abandoned carts recovered
    cart_recovery_revenue: float  # $ from recovery campaigns
    pricing_lift_pct: float  # % revenue lift from pricing optimization
    total_interventions_cost: float  # $ spent on discounts + campaigns
    total_incremental_revenue: float  # $ generated by interventions
    roi_multiplier: float  # Revenue / cost
    last_updated_iso: str


@dataclass
class UnifiedCustomerIntelligence:
    """Unified view of customer across all modules."""

    customer_id: str
    churn_risk_score: float
    churn_tier: str
    ltv_90day: float
    ltv_365day: float
    ltv_tier: str  # "low", "medium", "high"
    abandoned_carts_count: int
    total_abandoned_value: float
    intervention_history: List[Dict]  # [{type, date, response}]
    pricing_sensitivity: Optional[Dict] = None  # {avg_discount_accepted, response_rate}
    recommended_strategy: Optional[str] = None


@dataclass
class ModelPerformanceDashboard:
    """Model accuracy and drift monitoring."""

    churn_model_auc: float
    churn_model_auc_by_segment: Dict[str, float]  # {segment: auc}
    ltv_model_mae: float
    ltv_model_mae_by_cohort: Dict[str, float]  # {cohort: mae}
    recovery_model_auc: float
    elasticity_accuracy: Optional[float] = None
    drift_detected: bool = False
    drift_alert_msg: Optional[str] = None
    last_evaluated_iso: str = ""


@dataclass
class DataFreshness:
    """Data freshness timestamps."""

    cassandra_last_refresh_minutes_ago: int
    iceberg_last_refresh_hours_ago: int
    churn_scores_last_computed_hours_ago: int
    ltv_predictions_last_computed_hours_ago: int
    pricing_recommendations_last_computed_hours_ago: int
    cassandra_sla_minutes: int = 5
    iceberg_sla_hours: int = 24
    within_sla: bool = False


class DashboardService:
    """Business logic for unified insights and KPI aggregation."""

    def __init__(
        self,
        churn_service=None,
        ltv_service=None,
        cart_service=None,
        pricing_service=None,
        analytics_dao=None,
    ):
        """Initialize DashboardService.

        Args:
            churn_service: ChurnService instance
            ltv_service: LTVService instance
            cart_service: CartService instance
            pricing_service: PricingService instance
            analytics_dao: Optional DAO for analytics queries
        """
        self.churn_service = churn_service
        self.ltv_service = ltv_service
        self.cart_service = cart_service
        self.pricing_service = pricing_service
        self.analytics_dao = analytics_dao

    def get_kpi_summary(
        self,
        current_month_data: Optional[Dict] = None,
        previous_month_data: Optional[Dict] = None,
    ) -> DashboardKPIs:
        """Get unified KPI dashboard.

        Args:
            current_month_data: Current month's metrics (or compute from data)
            previous_month_data: Previous month's metrics (for YoY comparison)

        Returns:
            DashboardKPIs with all key metrics

        REQ-023: Unified Dashboard with Cross-Module Insights
        """
        # Defaults for demo
        current = current_month_data or {
            "churn_rate": 9.1,
            "avg_ltv": 520,
            "recovery_rate": 0.18,
            "recovery_revenue": 250000,
            "pricing_lift_pct": 3.2,
            "intervention_cost": 80000,
            "incremental_revenue": 370000,
        }
        previous = previous_month_data or {"churn_rate": 9.2, "avg_ltv": 505}

        churn_change = current["churn_rate"] - previous["churn_rate"]
        ltv_change_pct = (
            (current["avg_ltv"] - previous["avg_ltv"]) / previous["avg_ltv"] * 100
        )

        roi = (
            current["incremental_revenue"] / current["intervention_cost"]
            if current["intervention_cost"] > 0
            else 0
        )

        return DashboardKPIs(
            churn_rate=current["churn_rate"],
            churn_rate_change=churn_change,
            avg_ltv=current["avg_ltv"],
            ltv_change_pct=ltv_change_pct,
            cart_recovery_rate=current["recovery_rate"] * 100,
            cart_recovery_revenue=current["recovery_revenue"],
            pricing_lift_pct=current["pricing_lift_pct"],
            total_interventions_cost=current["intervention_cost"],
            total_incremental_revenue=current["incremental_revenue"],
            roi_multiplier=roi,
            last_updated_iso=datetime.utcnow().isoformat(),
        )

    def get_customer_intelligence(
        self,
        customer_id: str,
    ) -> Optional[UnifiedCustomerIntelligence]:
        """Get unified customer view across all modules.

        Args:
            customer_id: Customer ID

        Returns:
            UnifiedCustomerIntelligence with churn, LTV, cart, pricing views

        REQ-026: Unified Customer Intelligence & Explainability
        """
        if not self.churn_service or not self.ltv_service:
            logger.warning("Services not available for customer intelligence")
            return None

        try:
            # Get churn score
            churn_score = self.churn_service.score_customer(customer_id)

            # Get LTV prediction
            ltv_pred = self.ltv_service.predict_ltv(customer_id)

            # Determine LTV tier
            ltv_90day = ltv_pred.ltv_90day if ltv_pred else 0
            if ltv_90day > 500:
                ltv_tier = "high"
            elif ltv_90day > 200:
                ltv_tier = "medium"
            else:
                ltv_tier = "low"

            # Cross-module insight
            recommendation = self._generate_recommendation(
                churn_score.score, churn_score.tier, ltv_90day, ltv_tier
            )

            return UnifiedCustomerIntelligence(
                customer_id=customer_id,
                churn_risk_score=churn_score.score,
                churn_tier=churn_score.tier.value,
                ltv_90day=ltv_90day,
                ltv_365day=ltv_pred.ltv_365day if ltv_pred else 0,
                ltv_tier=ltv_tier,
                abandoned_carts_count=0,  # Would query from DAO
                total_abandoned_value=0,  # Would query from DAO
                intervention_history=[],  # Would query from DAO
                recommended_strategy=recommendation,
            )

        except Exception as e:
            logger.error(f"Error getting customer intelligence for {customer_id}: {e}")
            return None

    def get_model_performance(self) -> ModelPerformanceDashboard:
        """Get model performance metrics and drift detection.

        Args:
            None

        Returns:
            ModelPerformanceDashboard with AUC, MAE, drift alerts

        REQ-027: Model Performance Monitoring
        """
        return ModelPerformanceDashboard(
            churn_model_auc=0.82,  # Would compute from evaluation set
            churn_model_auc_by_segment={
                "new_customers": 0.78,
                "high_value": 0.85,
                "mobile": 0.75,
            },
            ltv_model_mae=45.0,  # $ MAE
            ltv_model_mae_by_cohort={
                "2024_q1": 42.0,
                "2024_q2": 50.0,
            },
            recovery_model_auc=0.76,
            elasticity_accuracy=0.88,
            drift_detected=False,
            drift_alert_msg=None,
            last_evaluated_iso=datetime.utcnow().isoformat(),
        )

    def get_data_freshness(
        self,
        cassandra_refresh_minutes_ago: int = 2,
        iceberg_refresh_hours_ago: int = 2,
        churn_computed_hours_ago: int = 3,
        ltv_computed_hours_ago: int = 3,
        pricing_computed_hours_ago: int = 3,
    ) -> DataFreshness:
        """Get data freshness and SLA status.

        Args:
            cassandra_refresh_minutes_ago: Minutes since last Cassandra refresh
            iceberg_refresh_hours_ago: Hours since last Iceberg refresh
            churn_computed_hours_ago: Hours since last churn scoring
            ltv_computed_hours_ago: Hours since last LTV prediction
            pricing_computed_hours_ago: Hours since last pricing recommendation

        Returns:
            DataFreshness with SLA compliance

        REQ-028: Data Freshness and Latency Transparency
        """
        cassandra_within_sla = cassandra_refresh_minutes_ago <= 5
        iceberg_within_sla = iceberg_refresh_hours_ago <= 24

        return DataFreshness(
            cassandra_last_refresh_minutes_ago=cassandra_refresh_minutes_ago,
            iceberg_last_refresh_hours_ago=iceberg_refresh_hours_ago,
            churn_scores_last_computed_hours_ago=churn_computed_hours_ago,
            ltv_predictions_last_computed_hours_ago=ltv_computed_hours_ago,
            pricing_recommendations_last_computed_hours_ago=pricing_computed_hours_ago,
            cassandra_sla_minutes=5,
            iceberg_sla_hours=24,
            within_sla=cassandra_within_sla and iceberg_within_sla,
        )

    @staticmethod
    def _generate_recommendation(
        churn_score: float,
        churn_tier: str,
        ltv_90day: float,
        ltv_tier: str,
    ) -> str:
        """Generate cross-module recommendation.

        Args:
            churn_score: Churn risk (0-100)
            churn_tier: Churn tier
            ltv_90day: 90-day LTV
            ltv_tier: LTV tier

        Returns:
            Recommendation string

        REQ-026: Cross-module insight
        """
        if churn_tier == "HIGH" and ltv_tier == "high":
            return "HIGH-VALUE AT RISK: Offer VIP service & personalized support (not discount)"
        elif churn_tier == "HIGH" and ltv_tier == "low":
            return "AT-RISK LOW-VALUE: Consider targeted email or light touch offer"
        elif churn_tier == "MEDIUM" and ltv_tier == "high":
            return "MEDIUM-RISK HIGH-VALUE: Send nurture content & exclusive offers"
        elif churn_tier == "MEDIUM" and ltv_tier == "low":
            return "STANDARD NURTURE: Regular engagement campaigns"
        else:
            return "STABLE CUSTOMER: Monitor for changes"
